### ISSUE TITLE
module not working properly during the installation process

### ISSUE THREAD

**Issue by poptartintoaster** [am0nt31r0/OSINT-Search#2]
Traceback (most recent call last):
  File "osintS34rCh.py";, line 10, in <module>;
    import validators
ModuleNotFoundError: No module named 'validators'

Is anyone else experiencing the following issue when attempt to run the script with python3?

**Comment by am0nt31r0** [comment]
try 'pip3 install validators'

**Comment by josephiyaya** [comment]
any help on this error.... raceback (most recent call last):
  File "osintS34rCh.py", line 14, in <module>
    from google import google
ImportError: cannot import name 'google' from 'google' (unknown location)

**Comment by Akashsena** [comment]
> any help on this error.... raceback (most recent call last):
> File "osintS34rCh.py", line 14, in
> from google import google
> ImportError: cannot import name 'google' from 'google' (unknown location)

Same Error is showing in my Also

**Comment by nitinnair95** [comment]
> any help on this error.... raceback (most recent call last):
> File "osintS34rCh.py", line 14, in
> from google import google
> ImportError: cannot import name 'google' from 'google' (unknown location)

In my case, the error was resolved after I updated my python version. Might work for you as well. Let me know.

**Comment by elliot7755** [comment]
Traceback (most recent call last):
  File "/root/OSINT-Search/osintS34rCh.py", line 14, in <module>
    from google import google
ImportError: cannot import name 'google' from 'google' (unknown location)

**Comment by Reginmand** [comment]
Как исправить эту ошибку `[~/OSINT-Search]
└─$ python3 osintS34rCh.py                    
Traceback (most recent call last):
  File "/home/air/OSINT-Search/osintS34rCh.py", line 14, in <module>
    from google import google
ImportError: cannot import name 'google' from 'google' (unknown location)
.` Эти методы не помогли:
1.0. Исправление ошибки функцию python3 -m pip install googlesearch-python (не помогла)
1.1. python3 -m pip install validators (не помогла)
1.2. python3 -m pip install google, python3 -m pip install --upgrade google (не помогла)
1.3. pip install --upgrade google-api-python-client (не помогла)
1.4. pip install google-cloud (не помогла)
1.5. pip install google-cloud-vision, pip install --upgrade google-cloud-translate (не помогла)
1.6. pip install google.cloud.bigquery (не помогла)
1.7. pip install google.cloud.storage (не помогла)
1.8. pip install protobuf (не помогла)
1.9. sudo pip install conda (не помогла)
1.10. pip install bigquery, pip install xyz-google-stuff (не помогла)
