### ISSUE TITLE
Keep getting permission issue on config.ini

### ISSUE THREAD

**Issue by JaySmith502** [am0nt31r0/OSINT-Search#4]
```
Traceback (most recent call last):                                                 File "osintS34rCh.py", line 809, in                                        if apiFile():                                                                  File "osintS34rCh.py", line 151, in apiFile                                        with open(filename, 'w') as configfile:                                      PermissionError: [Errno 13] Permission denied: '/osintSearch.config.in
--
```

I've tried updating the file permissions to allow writing from within osintS34rch.py but keep getting this error

**Comment by JaySmith502** [comment]
`

Traceback (most recent call last):
File "osintS34rCh.py", line 809, in
   if apiFile():
File "osintS34rCh.py", line 151, in apiFile
   with open(filename, 'w') as configfile:
   PermissionError: [Errno 13] Permission denied: '/osintSearch.config.in
--


`

**Comment by vicmac-github** [comment]
@JaySmith502 Did you solve the problem? a
![OSINT-Search error 13 (2)](https://user-images.githubusercontent.com/69369181/129363118-9446d5c3-8cb2-410f-8589-8723194e0f3c.JPG)
nd if you did it.... how? i have the same problem.  :s

**Comment by Lark-3301** [comment]
@JaySmith502 Did you solve the problem? and if you did it... how did you do it? I have the same error message.  :S

![OSINT-Search error 13 (2)](https://user-images.githubusercontent.com/69369181/129363325-6f4ff0f4-f2ea-45fd-bb57-242d40235a8f.JPG)

**Comment by JaySmith502** [comment]
I didn't 'solve' it per se, I removed the offending lines at the time and just lived without that functionality if I recall, but it's been a bit.
