### ISSUE TITLE
error in E-mail. 

### ISSUE THREAD

**Issue by meetgyn** [am0nt31r0/OSINT-Search#5]
[*] Full Name: †‡xxxxxxxx‡†
Traceback (most recent call last):
  File "osintS34rCh.py", line 825, in <module>
    fullcontact(sys.argv[2], fullcontact_key)
  File "osintS34rCh.py", line 683, in fullcontact
    for site in j['contactInfo']['websites']:
KeyError: 'websites'

**Comment by shanow7** [comment]
I've problem

![image](https://user-images.githubusercontent.com/37192410/73084148-bb02e100-3ecc-11ea-91dd-f42a7af5f2b3.png)
